Implement PSR-15
prooph/psr7-middleware pull request #24
Opened 2017-04-08 19:59 UTC by bgaleotti

Should close #21. Superseeds #23.

2017-04-08 20:14 UTC, sandrokeil commented
Is it useful to use [Problem Details](https://framework.zend.com/blog/2017-03-23-expressive-error-handling.html) responses on errors? But then we have to implement response classes and additional dependecies.

2017-04-09 12:14 UTC, prolic requested changes
looks good to me (besides some components that need to be upgraded), but I did not use any middleware application the last few months, so I am not 100% up to date, please as @basz for an additional review on this one.

2017-04-09 12:14 UTC, prolic commented on composer.json
>      "phpunit/phpunit": "^5.7",
upgrade to phpunit 6 please

2017-04-09 12:14 UTC, prolic commented on composer.json
>      "phpunit/phpunit": "^5.7",
upgrade to prooph/bookdown-template please

2017-04-09 12:14 UTC, prolic commented on composer.json
>      "phpunit/phpunit": "^5.7",
upgrade to prooph/common ^4.1 please

2017-04-09 12:48 UTC, basz reviewed
Lgtm

2017-04-09 13:04 UTC, prolic approved these changes

2017-04-09 19:13 UTC, codeliner approved these changes

2017-04-09 19:13 UTC, merged

2017-04-09 19:45 UTC, prolic commented
:+1:

2017-04-09 20:23 UTC, codeliner commented
@prolic should we wait with new release till travis-ci works again? A failed master build looks not so good

2017-04-10 02:47 UTC, prolic commented
Currently master build is red on all components, damn 7.1.3. We can wait
for 7.1.4 and wait again until travis is upgraded, too. Or we have yet
another red master, you decide


Am 10.04.2017 04:23 schrieb "Alexander Miertsch" <notifications@github.com>:

> @prolic <https://github.com/prolic> should we wait with new release till
> travis-ci works again? A failed master build looks not so good
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/prooph/psr7-middleware/pull/24#issuecomment-292810354>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAYEvGsRvwARWKwIcZFKv2wbVPsKHzT0ks5ruT4_gaJpZM4M30BP>
> .
>

2017-04-10 07:16 UTC, basz commented
Ik know that we can instruct travis to use a specific version of php but not how to tell is not to use a specific version as we would like

2017-04-11 05:51 UTC, prolic commented
I tagged https://github.com/prooph/psr7-middleware/releases/tag/v0.5